[package]
name = "lipsum-cli"
version = "0.1.0"
edition = "2021"
authors = ["Civan Yavuzsen <civanyavuzsen@gmail.com>"]
description = "Terminal application for generating lipsum text"
license = "MIT"

[dependencies]
atty = "0.2"
clap = { version = "3.1.0", features = ["derive"] }
lipsum = "0.8"

[dev-dependencies]
version-sync = "0.9"