name: Rust

on:
  push:
    tags: 
      - v[0-9]+.*
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

      - name: Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Publish            
        uses: katyo/publish-crates@v2
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      - name: Upgrade Brew Tap
        uses: chyroc/upgrade-brew-tap@v0.24.0
        with:
          name: "<tap-name>"
          tap_repo: "xlith/homebrew-lorem-ipsum"
          token: ${{ secrets.TAP_TOKEN }}
